dist: trusty
sudo: required
language: php
php:
  - 8.2

install: composer install

before_script:
  - pecl install parallel
	- docker-php-ext-enable parallel
	- EXTENSION_DIR=`php-config --extension-dir 2>/dev/null`
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - $HOME/.npm

script:
  - composer run test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack:
    secure: "w5dJh+4CbjTmr4f9SvzQ+e+70UfGucS3dFGkhKpchw6pAesPlNAYzcNrX+N/lhZfVfLVP2CR04GV26DTS40WZqMMxuQPGYqBz69vyy/FQ+hN7Qh4H7ZRvK1ooaTiY2S5U/BJ1B+knY/y57g8nGyIUj3mkhwrb9adY5D3B5+qWU1HwwWz1aJRNAUAHWI0ejr6dKosZXZHvp1azRspP6DjcXAmwhKlB5U8QBLTRyhrv3nFLbCoG/R0751b0uGIQmhIhM7huAa0kkGm77vffQbOCm8JhFXc28rS4kgZz7bLouTkhkQ7lIzxkHwEXngv/ON5X1mPcRmqP8iAcTx/BewKptwhgyLVEP7N2bi89cFYsDkBsUzMQlNupKUS2xwZP/aA8oRk5kRSh4yheDR8ajXZ1MENW9K0Y0b3WwTRme5EC3+SOGjdsaPIFfzwY6CBHO0aTKtvpx/Ll63ZfiEwpZYpDKOrcAhVoJMM1qu2+qCkqUN2hbymPOmTvwftiIZqRWT1LUAzbaVa2F6WWxOqgtVzgfzYQDocUXAu+McAd4zXjuAByxuN6A7zEW6xC5ZfjI5ouMjdD6Goos8qgVQpxIqXn3mlQ4dJeGvYj1BIpFFAmMKJomDx8pAXF1Huyjc2iKzeGrEZEA8XcugXYZS/XvtkS8eJeSboqacolCTE7ZvNzP0="
  email:
    recipients:
      - eldar@coralogix.com
    on_success: change
    on_failure: always